name: commitlint
on:
  pull_request:
    branches:
      - main
      - develop
      - 'feat/**'
      - 'fix/**'
      - 'chore/**'
permissions:
  contents: read
  pull-requests: read

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v6
