name: release-please-test
on:
  push:
    branches: [feat/changelog-and-versions]

permissions:
  contents: write
  pull-requests: write

jobs:
  rp-test:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: node
          target-branch: feat/changelog-and-versions
          skip-github-release: true
