name: Purge Vercel caches (CDN + Data)

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  schedule:
    - cron: "30 3 */3 * *"
  workflow_dispatch: {}

jobs:
  purge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: npm i -g vercel@latest

      - name: Purge CDN cache
        run: vercel cache purge --type=cdn --yes

      - name: Purge Data cache
        run: vercel cache purge --type=data --yes

