name: Purge Vercel caches (CDN + Data)
on:
  schedule:
    - cron: "30 3 */3 * *"
  workflow_dispatch: {}

jobs:
  purge:
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - run: npm i -g vercel@latest

      - name: Who am I
        run: vercel whoami --token "$VERCEL_TOKEN"

      - name: Purge CDN cache
        run: |
          vercel cache purge --type=cdn --yes \
            --token "$VERCEL_TOKEN" \
            --scope the-wildcat-protocol \
            --project wildcat-app-v2 \
          || vercel cache purge --type=cdn --yes \
            --token "$VERCEL_TOKEN" \
            --scope "${{ secrets.VERCEL_ORG_ID }}" \
            --project "${{ secrets.VERCEL_PROJECT_ID }}"

      - name: Purge Data cache
        run: |
          vercel cache purge --type=data --yes \
            --token "$VERCEL_TOKEN" \
            --scope the-wildcat-protocol \
            --project wildcat-app-v2 \
          || vercel cache purge --type=data --yes \
            --token "$VERCEL_TOKEN" \
            --scope "${{ secrets.VERCEL_ORG_ID }}" \
            --project "${{ secrets.VERCEL_PROJECT_ID }}"
